name: CI Workflow
on:
  push:
    branches:
      - main  # Adjust the branch if necessary
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false  # Disable submodule fetching
